### ISSUE TITLE
Some counter trigger error in event logs

### ISSUE THREAD

**Issue by pkolmann** [bloomberg/collectdwin#31]
Since upgrading from 0.5.8 to 0.5.14 I see a lot of errors in event log and it seems some counters trigger this.

If I only specify one counter, the problem doesn't surface, but with the attached WindowsPerformanceCounter.config I see a lot of these errors in the Event Log:

`ReadThreadProc() got exception : System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at BloombergFLP.CollectdWin.PerformanceCounterMetricGenerator.NextValues()
   at BloombergFLP.CollectdWin.WindowsPerformanceCounterPlugin.Read()
   at BloombergFLP.CollectdWin.MetricsCollector.ReadThreadProc(),    at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at BloombergFLP.CollectdWin.PerformanceCounterMetricGenerator.NextValues()
   at BloombergFLP.CollectdWin.WindowsPerformanceCounterPlugin.Read()
   at BloombergFLP.CollectdWin.MetricsCollector.ReadThreadProc()
`

The first few minutes I still get values but after some time, I don't get any output anymore.

System is a W2012R2 Server English Standard with GUI

[wpc.zip](https://github.com/bloomberg/collectdwin/files/270196/wpc.zip)

**Comment by pkolmann** [comment]
System is a W2012R2 Server English Standard with GUI
